### PR TITLE
DM-12693: Add upstream fix for linking problem with modern miniconda

### PR DESCRIPTION
**Pull request by timj**
This patch comes from GalSim-developers/GalSim#927 and does fix my problem.

### CODE REVIEW

**Comment by timj** [comment]
@danielsf it looks like @rmjarvis will be releasing a 1.5.1 with this patch relatively soon so that should allow you to finally update the LSST GalSim version.

**Comment by danielsf** [comment]
But this won't address  the meas_shapeHSM breakage, will it?

**Comment by timj** [comment]
Nope. shapeHSM needs fixing. You might end up being the person who does that fix depending on how desperate the community are for 1.5.1.

**Comment by danielsf** [comment]
Robert Armstrong backchanneled me.  Paul Price has him working on it.

https://github.com/GalSim-developers/GalSim/issues/925

**Comment by rmjarvis** [comment]
GalSim v1.5.1 is available: https://github.com/GalSim-developers/GalSim/releases/tag/v1.5.1

**Pull request merged**
