### PR TITLE
Feature/sim 1314/new gal sim patch

### PR DESCRIPTION
**Pull request by danielsf**
Up until now, we have been dealing with the fact that GalSim cannot build against anaconda's libpython2.7.dylib by having newinstall.sh use install_name_tool to change the install_name in that library from a relative to an absolute path.  This works, but as soon as the user runs conda update on their anaconda, the patch is undone.

This pull request adopts a more permanent solution by changing the install_names in the modules that load libpython2.7.dylib such that they can always find it.  This should be resilient to calls to conda update.

Once this ticket is merged, I will change newinstall.sh to get rid of the current install_name_tool patch.

Note: there is a supporting pull request in boost, since we have to do the same thing to libboost_python.dylib

### CODE REVIEW

**Comment by TallJimbo** [comment]
I know very little about linking on OS X, so I'm not really in a good position to review the actual changes here.  I do have some comments about the git history:
- This PR includes a commit from me that should already be on master.  Is that a duplicate from a rebase error?
- The other commit message is too long (should be < 50 chars for the first line), and doesn't describe the actual fix at all; see https://confluence.lsstcorp.org/display/LDMDG/Git+Commit+Best+Practices.

**Comment by danielsf** [comment]
I had to do a lot of hacking around to get this to work.  I then rebased everything into one commit, since it doesn't work unless you do all of this at once.  I don't know why your commit got pulled into that rebase.

I can make the commit message more explicit.

But... would you rather I sent the review to someone else?

What happens in this package doesn't worry me, since only a small corner of the sims team (and, I guess, DESC) cares about having GalSim come with the stack, but I wanted someone in DM to review this since I ended up having to touch boost as well, and that seemed like a very dangerous thing to do without letting it be more broadly known.

Let me know what you think.

**Comment by TallJimbo** [comment]
DM is actually using GalSim a bit too (dependency of meas_extensions_shapeHSM).  Anyhow, I'm happy to trust you that this solution works from a technical standpoint; if you're concerned about that, it'd be good to get another reviewer involved.

**Comment by danielsf** [comment]
Okay.  I will close this pull request and re-institute the changes cleanly (i.e. without your commit being considered part of the pull request).

Should I merge, then, or do you want to see the revised commit message?

**Comment by TallJimbo** [comment]
Go ahead and merge on your own.

**Pull request closed without merging**
